[package]
name = "bevy_mod_scripting_fennel"
version = "0.1.0"
edition = "2021"

[lib]
name = "bevy_mod_scripting_fennel"
path = "src/lib.rs"

[dependencies]
bevy_mod_scripting = { version = "0.5.0", features = ["lua51", "lua_script_api"] }
bevy_mod_scripting_lua = "0.5.0"
bevy_script_api = "0.5.0"
colored = "2.1.0"
log = "0.4.20"
mlua = "0.9.6"
rustyline = { version = "14.0.0", features = ["derive"] }
thiserror = "1"

[dependencies.bevy]
version = "0.13.0"
default-features = false
features = [
  "bevy_asset",
  "bevy_core_pipeline",
  "bevy_pbr",
  "bevy_render",
  "bevy_sprite",
  "bevy_winit",
#  "dynamic_linking",
  "file_watcher",
  "hdr",
  "multi-threaded",
  "serialize",
]
